### ISSUE TITLE
System.NullReferenceException on v1.0.39

### ISSUE THREAD

**Issue by BingFengHung** [madskristensen/WorkspaceFiles#13]
**Describe the bug**
無法建立檢視，發生例外狀況:
System.NullReferenceException: 並未將物件參考設定為物件的執行個體。
   於 WorkspaceFiles.WorkspaceRootNode.BuildAllDirectories() 於 D:\a\WorkspaceFiles\WorkspaceFiles\src\MEF\WorkspaceRootNode.cs: 行 86
   於 WorkspaceFiles.WorkspaceRootNode.get_Items() 於 D:\a\WorkspaceFiles\WorkspaceFiles\src\MEF\WorkspaceRootNode.cs: 行 75
   於 Microsoft.VisualStudio.PlatformUI.AggregateAttachedCollectionSource.InitializeItemCollection()
   於 Microsoft.VisualStudio.PlatformUI.AggregateAttachedCollectionSource.get_InnerItems()
   於 Microsoft.VisualStudio.PlatformUI.SolutionNavigatorPane.HookShowSolutionNodeEvents(IVsHierarchyItem solution)
   於 Microsoft.VisualStudio.PlatformUI.SolutionNavigatorPane.RefillNavigator(Boolean skipRestorePhase, Boolean isFirstLoad)

**To Reproduce**
Just open Solution then the error display.

**Screenshots**
![image](https://github.com/madskristensen/WorkspaceFiles/assets/21074416/605024cb-364c-458e-8fbe-e35a6adac815)

**Comment by madskristensen** [comment]
Fixed in latest version
