### ISSUE TITLE
Pin the virtual node to the top of Solution Explorer

### ISSUE THREAD

**Issue by timheuer** [madskristensen/WorkspaceFiles#22]
It seems the node basically is ordered alpha and sometimes it is at the bottom, which is less useful to me.

**Comment by madskristensen** [comment]
Does this happen immediately as the solution loads, or is it after using the Solution Explorer search field?

**Comment by timheuer** [comment]
immediately.

**Comment by timheuer** [comment]
Extensions manager isn't updating (found a bug) but will once it does work again ;-)
